version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Status"
          command: "echo Completed!"

workflows:
  build-workflow:
    jobs:
      - build